name: publish

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version-file: ".node-version"

      - name: Update npm
        run: npm install -g npm@latest

      - name: npm publish
        run: |
          npm ci
          npm run build
          npm publish
        if: contains(github.ref, 'tags/v')
        env:
          CI: true
